from .multiobjective.constrained import Srinivas, Tanaka
from .multiobjective.dtlz import *
from .multiobjective.lz09 import LZ09_F2
from .multiobjective.unconstrained import Fonseca, Kursawe, Schaffer, Viennet2
from .multiobjective.wfg import WFG1, WFG2, WFG3, WFG4, WFG5, WFG6, WFG7, WFG8, WFG9
from .multiobjective.zcat import (
    ZCAT1,
    ZCAT2,
    ZCAT3,
    ZCAT4,
    ZCAT5,
    ZCAT6,
    ZCAT7,
    ZCAT8,
    ZCAT9,
    ZCAT10,
    ZCAT11,
    ZCAT12,
    ZCAT13,
    ZCAT14,
    ZCAT15,
    ZCAT16,
    ZCAT17,
    ZCAT18,
    ZCAT19,
    ZCAT20,
)
from .multiobjective.zdt import ZDT1, ZDT2, ZDT3, ZDT4, ZDT5, ZDT6
from .singleobjective.tsp import TSP
from .singleobjective.unconstrained import OneMax, Sphere

__all__ = [
    "Srinivas",
    "Tanaka",
    "Kursawe",
    "Fonseca",
    "Schaffer",
    "Viennet2",
    "DTLZ1",
    "DTLZ2",
    "DTLZ3",
    "DTLZ4",
    "DTLZ5",
    "DTLZ6",
    "DTLZ7",
    "ZDT1",
    "ZDT2",
    "ZDT3",
    "ZDT4",
    "ZDT5",
    "ZDT6",
    "WFG1",
    "WFG2",
    "WFG3",
    "WFG4",
    "WFG5",
    "WFG6",
    "WFG7",
    "WFG8",
    "WFG9",
    "ZCAT1",
    "ZCAT2",
    "ZCAT3",
    "ZCAT4",
    "ZCAT5",
    "ZCAT6",
    "ZCAT7",
    "ZCAT8",
    "ZCAT9",
    "ZCAT10",
    "ZCAT11",
    "ZCAT12",
    "ZCAT13",
    "ZCAT14",
    "ZCAT15",
    "ZCAT16",
    "ZCAT17",
    "ZCAT18",
    "ZCAT19",
    "ZCAT20",
    "LZ09_F2",
    "OneMax",
    "Sphere",
    "TSP",
]
